#!/usr/bin/env node
/**
 * Self-contained build for the phone-standalone bundle. No parent repo, no PC.
 *
 *   npm install && npm run build
 *
 * Produces, per Android ABI, a ready-to-copy folder + zip:
 *
 *   dist/agent.js                        injectable script (all ABIs share it)
 *   dist/pixel-mobile-<abi>/             { agent.js, frida-inject-<abi>, launch.sh }
 *   dist/pixel-mobile-<abi>.zip          ^ zipped, drop on the phone & unzip
 *
 * agent.js = web assets + server shim + offset-injected compiled agent.
 */
const fs = require('fs');
const path = require('path');
const AdmZip = require('adm-zip');

const ROOT = __dirname;
const BUILD = path.join(ROOT, 'build');           // tsc output
const AGENT_JS = path.join(BUILD, 'agent.js');
const OFFSETS_JS = path.join(BUILD, 'offsets.js');
const SERVER = path.join(ROOT, 'src', 'server.js');
const WEB_DIR = path.join(ROOT, 'web');
const BIN = path.join(ROOT, 'bin');
const LAUNCH = path.join(ROOT, 'launch.sh');
const DIST = path.join(ROOT, 'dist');
const FRIDA_VERSION = '17.9.10';
const ARCHES = ['arm', 'arm64', 'x86', 'x86_64'];

const die = (m) => { console.error('[build] ' + m); process.exit(1); };

const WEB_BUILT = path.join(BUILD, 'web');   // generated by scripts/build-web.cjs

if (!fs.existsSync(AGENT_JS)) die('build/agent.js missing — run `tsc` (npm run build does this).');
if (!fs.existsSync(OFFSETS_JS)) die('build/offsets.js missing — run `tsc` first.');
if (!fs.existsSync(SERVER)) die('src/server.js missing.');
if (!fs.existsSync(path.join(WEB_BUILT, 'index.html'))) die('build/web/index.html missing — run `node scripts/build-web.cjs` first.');

// 1. inject offsets into the compiled agent (placeholders are JSON.parse('/*x*/'))
const off = require(OFFSETS_JS);
const placeholders = {
  '/*xaOffset*/': off._xaOffset,
  '/*anOffset*/': off._anOffset,
  '/*eposOffset*/': off._eposOffset,
  '/*xaPatch*/': off._xaPatch,
  '/*anPatch*/': off._anPatch,
  '/*agentSyms*/': off._symbols,
  '/*libName*/': off._libName,
};
let agent = fs.readFileSync(AGENT_JS, 'utf8');
let subs = 0;
for (const [token, value] of Object.entries(placeholders)) {
  const json = JSON.stringify(value);
  if (/['\\]/.test(json)) die(`offset ${token} has a quote/backslash; cannot inline.`);
  const esc = token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  agent = agent.replace(new RegExp(esc, 'g'), () => { subs++; return json; });
}
if (subs === 0) die('no offset placeholders substituted — stale build/agent.js?');

// 2. embed web assets: static PWA files (web/) + generated UI (build/web/)
const web = {};
for (const n of fs.readdirSync(WEB_DIR)) web['/' + n] = fs.readFileSync(path.join(WEB_DIR, n), 'utf8');
for (const n of fs.readdirSync(WEB_BUILT)) web['/' + n] = fs.readFileSync(path.join(WEB_BUILT, n), 'utf8');
web['/favicon.ico'] = web['/icon.svg'];   // login.ts points an <img> at ./favicon.ico

// 3. concatenate -> dist/agent.js
const banner =
  '// Pixel Mobile — generated by build.cjs. Do not edit by hand.\n' +
  '// Inject on a rooted phone with frida-inject. See README.md.\n';
const bundle = banner +
  'var __PIXEL_WEB__ = ' + JSON.stringify(web) + ';\n' +
  fs.readFileSync(SERVER, 'utf8') + '\n' + agent;

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });
fs.writeFileSync(path.join(DIST, 'agent.js'), bundle, 'utf8');

// 4. per-ABI ready-to-copy folders + zips
let zipped = 0;
for (const a of ARCHES) {
  const inject = path.join(BIN, `frida-inject-${FRIDA_VERSION}-android-${a}`);
  if (!fs.existsSync(inject)) { console.log(`[build] skip ${a} (no bundled frida-inject)`); continue; }
  const outDir = path.join(DIST, `pixel-mobile-${a}`);
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'agent.js'), bundle, 'utf8');
  fs.copyFileSync(inject, path.join(outDir, path.basename(inject)));
  fs.copyFileSync(LAUNCH, path.join(outDir, 'launch.sh'));
  const zip = new AdmZip();
  zip.addLocalFolder(outDir, `pixel-mobile-${a}`);
  zip.writeZip(path.join(DIST, `pixel-mobile-${a}.zip`));
  zipped++;
}

const kb = (Buffer.byteLength(bundle) / 1024).toFixed(0);
console.log(`[build] dist/agent.js (${subs} offset subs, ${Object.keys(web).length} web assets, ${kb} KB)`);
console.log(`[build] ${zipped} per-ABI bundle(s) in dist/`);
